kind: pipeline
type: docker
name: video-download-agent

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --single-branch --branch $DRONE_SOURCE_BRANCH --depth=1 $DRONE_GIT_HTTP_URL .

  - name: publish-dev
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: paulwrubel/video-download-agent
      tags:
        - dev
    when:
      branch:
        - main
      event:
        - push
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: paulwrubel/video-download-agent
      tags:
        - latest
        - prod
    when:
      branch:
        - main
      event:
        - tag
